import type { Metadata } from "next";
import { Azeret_Mono, DM_Sans } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const dmSans = DM_Sans({ variable: "--font-dm-sans", subsets: ["latin"] });
const azeretMono = Azeret_Mono({ variable: "--font-azeret-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${azeretMono.variable} antialiased`}
      >
        <header className="bg-brand-100 px-6 py-4">
          <nav className="flex items-center gap-6">
            <Link href="/" className="font-bold text-brand-50 hover:text-brand-600 transition-colors">
              Home
            </Link>
            <Link href="/users" className="text-brand-50 hover:text-brand-600 transition-colors">
              Users
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
